[package]
name = "up-wire-xcdrv2"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
up-rust = { git = "ssh://git@github.com/PLeVasseur/up-rust.git", rev = "815fbeb170f85e3bb33e98c63cfc4a2667dfb1f9", default-features = false }

[dev-dependencies]
trybuild = "1.0.114"
