[package]
name = "up-wire-xcdrv2"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
up-rust = { git = "https://github.com/PLeVasseur/up-rust.git", rev = "9e423a569eb9eb9c01a1585c74ac01a574ae6b8b", default-features = false, features = ["selected-wire-user-api", "wire-implementer-api", "zero-copy-transport"] }
up-wire-xcdrv2-macros = { path = "macros" }

[dev-dependencies]
static_assertions = "1.1"
trybuild = "1.0.114"
up-rust = { git = "https://github.com/PLeVasseur/up-rust.git", rev = "9e423a569eb9eb9c01a1585c74ac01a574ae6b8b", default-features = false, features = ["selected-wire-user-api", "transport-implementer-api", "wire-implementer-api", "zero-copy-transport"] }
