[package]
name = "up-wire-xcdrv2"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
up-rust = { git = "ssh://git@github.com/PLeVasseur/up-rust.git", rev = "98f62b4abefaa977ddfdcfcf8067b860f1303c64", default-features = false, features = ["selected-wire-protobuf-metadata", "selected-wire-transport-adapter"] }

[dev-dependencies]
trybuild = "1.0.114"
